title: Owen Lee's Portfolio
description: Show my capability!
#theme: just-the-docs
theme: just-the-docs
color_scheme: dark

url: https://owenducklee.github.io/OwenLee-Portfolio

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
