title: Owen Lee's Portfolio
description: This site is going to show my projects and learning path!
#theme: just-the-docs
theme: just-the-docs
color_scheme: dark

url: https://owenducklee.github.io/OwenLee-Portfolio

aux_links:
  Portfolio on GitHub: https://github.com/OwenDuckLee
